## <p style="color:red;">Numpy Arrays Introduction</p>

https://docs.scipy.org/doc/

In [47]:
data_list = [1,2,3]

In [48]:
data_list

[1, 2, 3]

In [49]:
import numpy as np

In [50]:
arr = np.array(data_list)

arr is a one dimension numpy array

In [51]:
arr

array([1, 2, 3])

#### We create a list of 3x3 as in the below

In [52]:
data_list2 = [[10,20,30,],[40,50,60,],[70,80,90]]

In [53]:
arr2 = np.array(data_list2)

In [54]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [55]:
arr2[2]

array([70, 80, 90])

In [56]:
arr2[2,2]

90

#### Range/Zeros/Ones/Linspace Methods

In [57]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [58]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [59]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### We can use tuple to create multiple dimension arrays

In [61]:
np.zeros((2,2)) 

array([[0., 0.],
       [0., 0.]])

In [62]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [63]:
np.random.randint(0,10)

7

In [64]:
np.random.randint(0,10,5)

array([7, 1, 1, 8, 4])

In [65]:
arr = np.arange(25)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
newArray = np.random.randint(1,100,10)

In [69]:
newArray

array([97, 88, 70, 42, 74, 89,  1, 62, 58, 59])

In [70]:
newArray.max()

97

In [71]:
newArray.argmax()   #shows the index number of max element

0

#### Determinant

In [72]:
deterArray = np.random.randint(1,100,25)

In [73]:
deterArray

array([17, 78,  9, 65, 28, 90, 42, 33, 26, 46, 31, 88, 46, 17, 72, 91, 90,
       77, 61, 37, 76,  8, 82, 43, 49])

In [74]:
deterArray = deterArray.reshape(5,5)

In [75]:
np.linalg.det(deterArray)

-1367407856.0000002

### Numpy Array Indexes

In [76]:
arr = np.arange(1,10)

In [77]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr[1]

2

In [79]:
arr[8]

9

In [80]:
arr[:4]

array([1, 2, 3, 4])

In [81]:
arr[::2]

array([1, 3, 5, 7, 9])

#### copy an array with a new memory space

In [82]:
arr = np.arange(1,10)

In [83]:
arr2 = arr.copy() #*******************

In [84]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr2[:3] = 0

In [87]:
arr2

array([0, 0, 0, 4, 5, 6, 7, 8, 9])

In [88]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
newArray =np.arange(1,21)

In [90]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [91]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [92]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [93]:
newArray = newArray.reshape(5,4)

In [94]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [95]:
newArray[0,0]

1

In [96]:
newArray[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [97]:
newArray[:3 , :3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [98]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [100]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [102]:
arr[arr >3]

array([4, 5, 6, 7, 8, 9])

## <p style="color:red;"> Numpy Array Basic Operations and Functions</p>

Mathematical Operations within the same dimensions

In [103]:
arr1 = np.array([10,20,30,40,50,60])

In [104]:
arr2 = np.array([2,3,4,5,6,7])

In [105]:
arr1 + arr2

array([12, 23, 34, 45, 56, 67])

In [106]:
arr1 - arr2

array([ 8, 17, 26, 35, 44, 53])

In [107]:
arr1 -2

array([ 8, 18, 28, 38, 48, 58])

In [108]:
np.sqrt(arr2)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131])

## Exercises

1. Import Numpy

In [ ]:
import numpy as np

2. Create an 1x5 array with ones

In [110]:
np.ones(5)

array([1., 1., 1., 1., 1.])

3. Create an 1x5 array with zeros

In [111]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

4. Create an array from 2 to 100 which are even

In [112]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5. Create an array contains 5 times 10

In [113]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [ ]:
6. Create an 4x4 array from 1 to 16

In [114]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

7. Generate random values between 0 -5.

In [115]:
np.random.rand()

0.9064251508376623

In [210]:
np.random.randint(0,6)

3

In [ ]:
8.Create a 1x20 dimension array from the values 1-5

In [211]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])